version: '3.8'

services:
  # Conteneur HTTP avec NGINX
  http:
    image: nginx:latest
    container_name: HTTP_3
    ports:
      - "8082:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf # Configuration de Nginx
      - ./src:/var/www/html  # Fichiers WordPress
    depends_on:
      - script
    networks:
      - webnet

  # Conteneur PHP avec PHP-FPM
  script:
    image: php:7.4-fpm
    container_name: SCRIPT_3
    volumes:
      - ./src:/var/www/html  # Fichiers WordPress
    depends_on:
      - data
    networks:
      - webnet


  # Installation de l'extension MySQLi
    command: >
      sh -c "docker-php-ext-install mysqli && php-fpm"

  # Conteneur MariaDB
  data:
    image: mariadb:latest
    container_name: DATA_3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
    driver: bridge
