version: '3.8'

services:
  # Conteneur HTTP avec NGINX
  http:
    image: nginx:latest
    container_name: HTTP_2
    ports:
      - "8081:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf # Config NGINX
      - ./src:/app # Fichiers source
    depends_on:
      - script
    networks:
      - webnet

  # Conteneur PHP avec PHP-FPM
  script:
    build:
      context: .
      dockerfile: Dockerfile
    #image: php:7.4-fpm
    container_name: SCRIPT_2
    volumes:
      - ./src:/app # Fichiers source
#    depends_on:
 #     - data
    networks:
      - webnet

  # Conteneur MariaDB
  data:
    image: mariadb:latest
    container_name: DATA
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
