version: '3'

services:
  # Conteneur HTTP avec NGINX
  http:
    image: nginx:latest
    container_name: HTTP
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - webnet

  # Conteneur PHP avec PHP-FPM
  php:
    image: php:7.4-fpm
    container_name: SCRIPT
    volumes:
      - ./src:/var/www/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
