version: '3.8'

services:
  http:
    image: nginx:latest
    container_name: HTTP_2
    ports:
      - "8080:80"  # Mappe le port 8080 de la machine hôte au port 80 du container
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf  # Configuration Nginx
      - ./src:/var/www/html  # Monté sur /var/www/html pour WordPress
    depends_on:
      - script
    networks:
      - webnet

  script:
    image: php:7.4-fpm  # Utiliser l'image PHP avec FPM
    container_name: SCRIPT_2
    volumes:
      - ./src:/var/www/html  # Monté sur /var/www/html pour WordPress
    depends_on:
      - data
    networks:
      - webnet

  data:
    image: mariadb:latest
    container_name: DATA
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress_db  # Créer une base de données pour WordPress
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - ./db_data:/var/lib/mysql  # Volume pour stocker les données
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

